version: "3.9"
services:
  firestore:
    platform: linux/amd64
    build: ./firestore
    ports:
      - 6641:6641
    environment:
      - PROJECT_ID=charaxiv
      - PORT=6641
    volumes:
      - ./firestore:/firestore
  
  backend:
    platform: linux/amd64
    build: ./backend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./gcp-credentials.json      
      - FIRESTORE_EMULATOR_HOST=firestore:6641
      - STORAGE_BUCKET_NAME=charaxiv-assets-local
      - FRONTEND_HOST=*
      - PORT=6640
    volumes:
      - ./backend:/app
    ports:
      - 6640:6640
    command: air
  
  frontend:
    platform: linux/amd64
    build: ./frontend
    environment:
      - IMAGE_HOST=https://storage.googleapis.com/charaxiv-assets-local
      - NEXT_PUBLIC_IMAGE_HOST=https://storage.googleapis.com/charaxiv-assets-local
      - BACKEND_HOST=http://backend:6640
      - NEXT_PUBLIC_BACKEND_HOST=http://localhost:6640
      - PORT=6650
    volumes:
      - ./frontend:/app
    ports:
      - 6650:6650
  