version: '3.0'
services:
  backend:
    build:
      dockerfile_inline: |
        FROM python:3.11.1-bullseye

        RUN apt-get update && apt-get install -y sqlite3 && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*
        RUN pip install --upgrade pip && pip install poetry 
    working_dir: /app
    volumes:
      - .:/app:cached
      - /app/.venv
      - /app/frontend
      - db_volume:/db:cached
      - venv_volume:/venv:cached
    environment:
      - STARLETTE_ENV=development
      - STARLETTE_KEY=starlette_key
      - CHARAXIV_HOST=localhost
      - CHARAXIV_PORT=6640
      - CHARAXIV_NOREPLY_EMAIL=noreply@charaxiv.app
      - CHARAXIV_CUSTOM_HEADER=X-CHARAXIV-CSRF-PROTECTION
      - SHEET_IMAGE_MAX_SIZE=1024
      - SQLITE_PATH=/db/charaxiv.db
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_SES_REGION_NAME=ap-northeast-1
      - AWS_SES_ENDPOINT_URL=
    entrypoint: [ "/app/scripts/entrypoint.dev.sh" ]
    command:
      - "poetry"
      - "run"
      - "uvicorn"
      - "--reload"
      - "--host=0.0.0.0"
      - "--lifespan=on"
      - "charaxiv.application:main"
    init: true

  frontend:
    image: node:18.8.0-bullseye
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
      - node_modules_volume:/app/node_modules:cached
    environment:
      - VITE_CHARAXIV_FQDN=http://localhost:6640
      - VITE_CHARAXIV_CUSTOM_HEADER=X-CHARAXIV-CSRF-PROTECTION
    entrypoint: [ "/app/scripts/entrypoint.dev.sh" ]
    command: npm run dev -- --host
    depends_on:
      - backend
    init: true

  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:cached
    depends_on:
      - frontend
      - backend

volumes:
  venv_volume:
  node_modules_volume:
  db_volume:
