[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["ktnyt <mirei.itaya@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.4"
pydantic = "^1.10.2"
gunicorn = "^20.1.0"
email-validator = "^1.3.0"
lazy-loader = "^0.1"
psycopg2 = "^2.9.5"
uuid6 = "^2022.10.25"
base58 = "^2.1.1"
python-json-logger = "^2.0.6"
injector = "^0.20.1"
pillow = "^9.4.0"
boto3 = "^1.26.99"
boto3-stubs = {extras = ["s3", "ses"], version = "^1.26.99"}
django-extensions = "^3.2.1"
sentry-sdk = "^1.24.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
flake8 = "^6.0.0"
autopep8 = "^2.0.1"
django-stubs = "^1.13.1"
coverage = "^6.5.0"
pytest-cov = "^4.0.0"
isort = "^5.11.2"
pytest-django = "^4.5.2"
autoflake = "^2.0.0"
faker = "^15.3.4"
django-extensions = "^3.2.1"
types-mock = "^4.0.15.2"
msgpack-types = "^0.2.0"
mypy = "^1.1.1"
types-pillow = "^9.4.0.17"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 200

[tool.mypy]
strict = true
disable_error_code = ["type-abstract"]
plugins = ["mypy_django_plugin.main"]
exclude = [
]

[tool.django-stubs]
django_settings_module = "app.settings"

[tool.coverage.run]
omit = [
    # Django generated files
    "app/asgi.py",
    "app/wsgi.py",
    "app/urls.py",
    "manage.py",

    # Test files
    "*_tests.py",

    # Settings files
    "app/settings/*.py",
]

[tool.pytest.ini_options]
python_files = "*_tests.py"
DJANGO_SETTINGS_MODULE = "app.settings"
