# Generated by Django 4.1.7 on 2023-03-29 06:08

import app.modules.model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name_key', models.TextField()),
                ('name_tag', models.IntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name_key', 'name_tag')},
            },
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=43, unique=True)),
                ('registered_at', models.DateTimeField()),
            ],
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=43, unique=True)),
                ('requested_at', models.DateTimeField()),
            ],
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
    ]
