# Generated by Django 4.1.7 on 2023-03-29 06:08

import app.modules.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
    ]
