# Generated by Django 4.1.7 on 2023-03-29 06:08

import app.modules.model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_repo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sheets', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_repo.system')),
            ],
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='SheetTag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField()),
                ('value', models.CharField(max_length=255)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='sheet_repo.sheet')),
            ],
            options={
                'unique_together': {('sheet', 'value'), ('sheet', 'index')},
            },
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='SheetImage',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_set', to='sheet_repo.sheet')),
            ],
            options={
                'unique_together': {('sheet', 'index')},
            },
            bases=(models.Model, app.modules.model.TimestampMixin),
        ),
    ]
