name: Python package

on:
  push:
    branches:
      - "**"

env:
  DJANGO_ENV: development
  SECRET_KEY: secret_key
  SERVICE_FQDN: https://charaxiv.app
  SERVICE_NOREPLY_ADDRESS: support-noreply@charaxiv.app
  SHEET_IMAGE_MAX_SIZE: 1024
  POSTGRES_DB: charaxiv
  POSTGRES_USER: charaxiv
  POSTGRES_PASSWORD: charaxiv
  POSTGRES_HOSTNAME: localhost
  AWS_ACCESS_KEY_ID: root
  AWS_SECRET_ACCESS_KEY: password
  AWS_S3_BUCKET_NAME: charaxiv_media
  AWS_S3_REGION_NAME: ap-northeast-1
  AWS_S3_ENDPOINT_URL: http://minio:9000
  AWS_SES_REGION_NAME: ap-northeast-1
  AWS_SES_ENDPOINT_URL:
  SENTRY_DSN: dummy

jobs:
  test-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          poetry install

      - name: Run coverage check
        run: |
          ./scripts/coverage.sh

      - name: Run integration tests
        run: |
          ./scripts/integration.sh
